name: app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^2.1.2
  rxdart: ^0.21.0
  font_awesome_flutter: ^8.4.0
  animated_card: ^1.0.0+5
  bloc_pattern: ^2.1.0
  rect_getter: ^0.0.1
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter:
  uses-material-design: true

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/icon/flutterando_icon.png"